# Generated by Django 6.0.6 on 2026-06-21 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_label', models.CharField(default='GST', max_length=50)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('access_type', models.CharField(choices=[('paid', 'Paid Subscription'), ('admin_grant', 'Granted by Admin'), ('free_tier', 'Free Tier')], default='free_tier', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
