# Generated by Django 6.0.6 on 2026-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_tenants_ten_is_acti_8f654a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
