# Generated by Django 6.0.6 on 2026-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_business_address_tenant_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free Tier'), ('pro', 'Pro — ₹499/mo'), ('enterprise', 'Enterprise — ₹999/mo'), ('admin_grant', 'Granted by Admin')], default='free', max_length=20),
        ),
    ]
