# Generated by Django 6.0.6 on 2026-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_plan_structure_free_pro_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
