# Generated by Django 5.2.16 on 2026-07-18 15:17
#
# Sandbox-verified on Django 5.2.16 (Python 3.10) — production runs Django
# 6.0.6. This is a plain choices-list change on an existing CharField
# (adds 'basic' as a new option, no column type / max_length change),
# identical behavior on both versions.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free Tier'), ('basic', 'Basic — ₹249/mo'), ('pro', 'Pro — ₹499/mo'), ('enterprise', 'Enterprise — ₹999/mo'), ('admin_grant', 'Granted by Admin')], default='free', max_length=20),
        ),
    ]
