# Generated by Django 6.0.6 on 2026-06-28 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('workspace_entered', 'Workspace Entered'), ('workspace_exited', 'Workspace Exited'), ('mode_switched', 'Mode Switched'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated'), ('customer_deleted', 'Customer Deleted'), ('invoice_status_changed', 'Invoice Status Changed')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_support_action', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='superadmin__tenant__4d21cc_idx'), models.Index(fields=['actor', '-created_at'], name='superadmin__actor_i_0c1399_idx'), models.Index(fields=['is_support_action', '-created_at'], name='superadmin__is_supp_19e130_idx')],
            },
        ),
    ]
