# Generated by Django 6.0.6 on 2026-07-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDeletionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id_snapshot', models.UUIDField()),
                ('tenant_name', models.CharField(max_length=255)),
                ('owner_email', models.CharField(blank=True, max_length=255)),
                ('products_count', models.IntegerField(default=0)),
                ('customers_count', models.IntegerField(default=0)),
                ('invoices_count', models.IntegerField(default=0)),
                ('users_count', models.IntegerField(default=0)),
                ('deleted_by_email_snapshot', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
