# Generated by Django 6.0.6 on 2026-07-18
# (dev-verified against Django 5.2.16 in an isolated sandbox — see note
# in teams/migrations/0008_viewassession.py for why. Real project/Render
# run Django 6.0.6; these operations are identical between the two.)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_alter_auditlog_action'),
        ('teams', '0012_alter_activitylog_action'),
        ('tenants', '0005_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('workspace_entered', 'Workspace Entered'), ('workspace_exited', 'Workspace Exited'), ('mode_switched', 'Mode Switched'), ('view_as_started', 'View As Started'), ('view_as_ended', 'View As Ended'), ('view_as_mode_switched', 'View As Mode Switched'), ('member_invited', 'Member Invited'), ('member_suspended', 'Member Suspended'), ('member_reactivated', 'Member Reactivated'), ('member_removed', 'Member Removed'), ('role_changed', 'Role Changed'), ('primary_owner_transferred', 'Primary Owner Transferred'), ('platform_case_opened', 'Platform Case Opened'), ('platform_case_closed', 'Platform Case Closed'), ('password_reset', 'Password Reset'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated'), ('customer_deleted', 'Customer Deleted'), ('invoice_status_changed', 'Invoice Status Changed')], max_length=50),
        ),
        migrations.CreateModel(
            name='PlatformCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('forced_ownership_transfer', 'Forced Ownership Transfer'), ('account_recovery', 'Account Recovery')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('reason', models.TextField()),
                ('identity_verification_notes', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolution_details', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_cases_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_cases_executed', to=settings.AUTH_USER_MODEL)),
                ('target_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_cases_as_target', to='teams.membership')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_cases_as_target', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_cases', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='superadmin__tenant__2b979c_idx'), models.Index(fields=['status', '-created_at'], name='superadmin__status_5a9120_idx')],
            },
        ),
    ]
