# Generated by Django 6.0.6 on 2026-06-29 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_number_per_tenant_unique'),
        ('tenants', '0002_tenant_tenants_ten_is_acti_8f654a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='billing_inv_tenant__f82d44_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', '-created_at'], name='billing_inv_tenant__8e7cfe_idx'),
        ),
    ]
