# Generated by Django 6.0.6 on 2026-07-04 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_billing_inv_tenant__f82d44_idx_and_more'),
        ('inventory', '0003_alter_product_unique_together_and_more'),
        ('tenants', '0005_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('restock', 'Restock Needed'), ('dead_stock', 'Dead Stock'), ('overdue', 'Overdue Collection')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('priority_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('acted', 'Acted On'), ('dismissed', 'Dismissed')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
