# Generated by Django 6.0.6 on 2026-07-05 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_estimates_quotes'),
        ('tenants', '0005_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.IntegerField()),
                ('cash_score', models.IntegerField()),
                ('sales_score', models.IntegerField()),
                ('inventory_score', models.IntegerField()),
                ('operations_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
