# Generated by Django 6.0.6 on 2026-07-07 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_expense_tracking'),
        ('inventory', '0007_units_per_box'),
        ('tenants', '0005_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('dense', 'Dense (regular sales)'), ('intermittent', 'Intermittent (sparse sales)'), ('insufficient_data', 'Insufficient Data')], max_length=20)),
                ('forecast_daily_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('data_points_used', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product'), name='unique_forecast_per_product')],
            },
        ),
    ]
