# Generated by Django 5.2.16 on 2026-07-22 07:36
#
# Sandbox-verified on Django 5.2.16 (Python 3.10) — production runs Django
# 6.0.6. Two plain nullable/defaulted AddField ops on existing tables,
# no data migration needed — identical behavior on both versions.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_demand_forecasting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
