# Generated by Django 6.0.6 on 2026-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0002_tenant_tenants_ten_is_acti_8f654a_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_p_tenant__2cb5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'stock_quantity'], name='inventory_p_tenant__4d2003_idx'),
        ),
    ]
