# Generated by Django 6.0.6 on 2026-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_inventory_p_tenant__2cb5ab_idx_and_more'),
        ('tenants', '0002_tenant_tenants_ten_is_acti_8f654a_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'sku'), name='unique_active_sku_per_tenant'),
        ),
    ]
