# Generated by Django 6.0.6 on 2026-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchase_orders_and_cbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_split_method',
            field=models.CharField(choices=[('equal', 'Equally across items'), ('by_quantity', 'By quantity'), ('by_value', 'By item value (cost × qty)'), ('by_volume', 'By volume (CBM)')], default='by_value', max_length=20),
        ),
    ]
