# Generated by Django 6.0.6 on 2026-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_freight_charges_and_wac'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='volume_cbm_override',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
