# Generated by Django 6.0.6 on 2026-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_volume_cbm_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='units_per_box_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
