# Generated by Django 6.0.6 on 2026-07-11 07:21
# (dev-verified against Django 5.2.16 in an isolated sandbox — this
# sandbox's Python is 3.10 and can't install 6.0.6, which requires 3.12+.
# Real project/Render both run Django 6.0.6. Migration operations below
# are identical between the two versions.)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_add_purchase_order_delete_permission'),
        ('tenants', '0005_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAsSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit Simulation')], default='view', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('manual', 'Manual Exit'), ('target_role_changed', 'Target Role Changed'), ('target_suspended', 'Target Suspended'), ('target_removed', 'Target Removed'), ('business_suspended', 'Business Suspended'), ('founder_support_ended', 'Founder Support Session Ended'), ('initiator_logged_out', 'Initiator Logged Out'), ('superseded', 'Superseded By New Session')], default='', max_length=30)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_as_sessions_started', to=settings.AUTH_USER_MODEL)),
                ('target_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_as_sessions_targeting', to='teams.membership')),
                ('target_role_at_start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_as_sessions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['initiator', 'is_active'], name='teams_viewa_initiat_4b8a7c_idx'), models.Index(fields=['tenant', 'is_active'], name='teams_viewa_tenant__a357fd_idx'), models.Index(fields=['target_membership', 'is_active'], name='teams_viewa_target__3cc3a1_idx')],
            },
        ),
    ]
