# Generated by Django 6.0.6 on 2026-07-12 04:39
# (dev-verified against Django 5.2.16 in an isolated sandbox — see note
# in teams/migrations/0008_viewassession.py for why. Real project/Render
# run Django 6.0.6; these operations are identical between the two.)

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_viewassession'),
        ('tenants', '0005_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_primary_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_owner', True)), fields=('tenant',), name='unique_active_primary_owner_per_tenant'),
        ),
    ]
