# Generated by Django 6.0.6 on 2026-07-18
# (dev-verified against Django 5.2.16 in an isolated sandbox — see note
# in teams/migrations/0008_viewassession.py for why. Real project/Render
# run Django 6.0.6; this AlterField operation is identical between the two.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('member_invited', 'Member Invited'), ('member_joined', 'Member Joined'), ('member_suspended', 'Member Suspended'), ('member_reactivated', 'Member Reactivated'), ('member_removed', 'Member Removed'), ('role_changed', 'Role Changed'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('primary_owner_transferred', 'Primary Owner Transferred'), ('password_reset', 'Password Reset'), ('view_as_started', 'View As Started'), ('view_as_ended', 'View As Ended'), ('view_as_mode_switched', 'View As Mode Switched'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated'), ('customer_deleted', 'Customer Deleted'), ('invoice_status_changed', 'Invoice Status Changed')], max_length=50),
        ),
    ]
