import requests
from django.conf import settings


def send_telegram_message(chat_id, text):
    """
    Telegram bot se message bhejo.
    Bot token environment variable se aata hai (secret, code mein nahi likha).
    Returns: (success: bool, error_message: str or None)
    """
    if not settings.TELEGRAM_BOT_TOKEN:
        return False, "Telegram bot not configured on server."

    if not chat_id:
        return False, "No Telegram Chat ID set for this business."

    url = f"https://api.telegram.org/bot{settings.TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        'chat_id': chat_id,
        'text': text,
        'parse_mode': 'HTML',
    }

    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            return True, None
        else:
            return False, f"Telegram API error: {response.json().get('description', 'Unknown error')}"
    except requests.exceptions.RequestException as e:
        return False, f"Could not reach Telegram: {str(e)}"


def build_daily_summary_message(tenant, date, subtotal, tax_amount, total_amount, total_profit, invoice_count, currency):
    """
    Formatted daily summary message banao — HTML formatting Telegram ke liye.
    """
    sym = {'INR': '₹', 'USD': '$', 'AED': 'AED ', 'GBP': '£', 'EUR': '€'}.get(currency, currency + ' ')

    return (
        f"<b>📊 Daily Report — {tenant.name}</b>\n"
        f"<i>{date.strftime('%d %B %Y')}</i>\n\n"
        f"🧾 Invoices: <b>{invoice_count}</b>\n"
        f"💰 Revenue: <b>{sym}{total_amount:,.2f}</b>\n"
        f"📈 Profit: <b>{sym}{total_profit:,.2f}</b>\n\n"
        f"<i>Subtotal: {sym}{subtotal:,.2f} · Tax: {sym}{tax_amount:,.2f}</i>\n\n"
        f"Generated by BillingMars"
    )